# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CricketTeamModel',
            fields=[
                ('team_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_captain', models.CharField(max_length=100)),
            ],
        ),
    ]
