# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
